### ISSUE TITLE
Reinforced Core GUIs Don't Respect Changes to GUI Textures by Resource Packs

### ISSUE THREAD

**Issue by Ice-Arrow** [Aton-Kish/reinforced-core#21]
I'm attempting to add support for Reinforced Chests/Barrels/Shulkers to the Default Darkmode Resource Pack by creating dark mode versions of the GUIs used for this mod. I'm not entirely certain if this is a bug or something I'm doing wrong, I'm hardly a coder, but it looks like your GUIs are based off of \textures\gui\demo_background and \textures\gui\container\generic_54. The issue is that even when I change those two textures with a resource pack the GUIs for your inventories aren't affected. Like I said it's possible I'm just doing it wrong on my end, in which case I apologize for wasting your time, but I'm unsure what else to try. I've attached [my stripped down testing version of Default Darkmode](https://github.com/Aton-Kish/reinforced-core/files/9561986/Darkmode.Testing.zip) that I've been using while troubleshooting in case that's of any help. 

Thank you for your time

**Comment by Aton-Kish** [comment]
Hi,
I recently modified the screen textures. However, I did in ONLY version 1.19 because I didn't have enough time.
[The default dark mode resource pack](https://www.curseforge.com/minecraft/texture-packs/default-dark-mode) works well in version 1.19. So please check your environment version.

**Comment by Ice-Arrow** [comment]
I apologize I should have been more clear, I am working exclusively on 1.18 at the moment as that's the main version I currently play on. I just wanted to make sure it wasn't something I was doing wrong which was stopping the GUI textures from changing. I understand time limitations can be difficult and I appreciate your help, issue closed.

**Comment by Aton-Kish** [comment]
updated screen textures in 1.18.2 too.

**Comment by Ice-Arrow** [comment]
Sweet, thanks for coming back and fixing this issue up. I appreciate you taking the time out of your day to work on this issue even though it's for an outdated version of minecraft.
