### ISSUE TITLE
[Feature] API for ReinforcedStorageScreenHandler

### ISSUE THREAD

**Issue by gbl** [Aton-Kish/reinforced-core#4]
### Describe the solution you'd like

I was asked by a user of my EasierChests mod if it would be possible to add support for Reinforced Chests  (https://github.com/gbl/EasierChests/issues/10). I guess this would automatically work with shulkers and barrels as well, as all of them use the same screen handler.

I can add partial support, but to support your chests completely, I'd need to know how many rows and columns there are in a container. Looking at your source, it seems like I can check the inventory size, calculate cols from what you're doing in line 82, and rows by dividing size by cols, but that seems terribly fragile to me in case you ever change your code.

Would you mind adding a getCols() and a getRows() method to your ReinforcedStorageScreenHandler?  Then I could just use those and be less dependent on your internals, and I could check if the ScreenHandler is instanceof yours, and call those methods in that case. 

Thanks! Giselbaer

**Comment by Aton-Kish** [comment]
In version 1.1.0, added `getColumns()`/`getRows()` methods to ReinforcedStorageScreenHandler:)
